# This workflow is dedicated to host slow jobs that are run only periodically because
# they are too slow to run in every commit.  The list of slow tests can be found in
# https://github.com/pytorch/test-infra/blob/generated-stats/stats/slow-tests.json
name: slow

on:
  schedule:
    - cron: 45 0,4,8,12,16,20 * * *
    - cron: 29 8 * * *  # about 1:29am PDT, for mem leak check and rerun disabled tests
  push:
    tags:
      - ciflow/slow/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}-${{ github.event.schedule }}
  cancel-in-progress: true

jobs:
  linux-bionic-cuda11_7-py3-gcc7-slow-gradcheck-build:
    name: linux-bionic-cuda11.7-py3-gcc7-slow-gradcheck
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-bionic-cuda11.7-py3-gcc7-slow-gradcheck
      docker-image-name: pytorch-linux-bionic-cuda11.7-cudnn8-py3-gcc7
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 4, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 2, num_shards: 4, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 3, num_shards: 4, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 4, num_shards: 4, runner: "linux.4xlarge.nvidia.gpu" },
        ]}

  linux-bionic-cuda11_7-py3-gcc7-slow-gradcheck-test:
    name: linux-bionic-cuda11.7-py3-gcc7-slow-gradcheck
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-bionic-cuda11_7-py3-gcc7-slow-gradcheck-build
    with:
      build-environment: linux-bionic-cuda11.7-py3-gcc7-slow-gradcheck
      docker-image: ${{ needs.linux-bionic-cuda11_7-py3-gcc7-slow-gradcheck-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-bionic-cuda11_7-py3-gcc7-slow-gradcheck-build.outputs.test-matrix }}
      timeout-minutes: 300

  linux-bionic-cuda11_7-py3_10-gcc7-sm86-build:
    name: linux-bionic-cuda11.7-py3.10-gcc7-sm86
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-bionic-cuda11.7-py3.10-gcc7-sm86
      docker-image-name: pytorch-linux-bionic-cuda11.7-cudnn8-py3-gcc7
      cuda-arch-list: 8.6
      test-matrix: |
        { include: [
          { config: "slow", shard: 1, num_shards: 2, runner: "linux.g5.4xlarge.nvidia.gpu" },
          { config: "slow", shard: 2, num_shards: 2, runner: "linux.g5.4xlarge.nvidia.gpu" },
        ]}

  linux-bionic-cuda11_7-py3_10-gcc7-sm86-test:
    name: linux-bionic-cuda11.7-py3.10-gcc7-sm86
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-bionic-cuda11_7-py3_10-gcc7-sm86-build
    with:
      build-environment: linux-bionic-cuda11.7-py3.10-gcc7-sm86
      docker-image: ${{ needs.linux-bionic-cuda11_7-py3_10-gcc7-sm86-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-bionic-cuda11_7-py3_10-gcc7-sm86-build.outputs.test-matrix }}

  linux-bionic-py3_8-clang9-build:
    name: linux-bionic-py3.8-clang9
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-bionic-py3.8-clang9
      docker-image-name: pytorch-linux-bionic-py3.8-clang9
      test-matrix: |
        { include: [
          { config: "slow", shard: 1, num_shards: 1, runner: "linux.2xlarge" },
        ]}

  linux-bionic-py3_8-clang9-test:
    name: linux-bionic-py3.8-clang9
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-bionic-py3_8-clang9-build
    with:
      build-environment: linux-bionic-py3.8-clang9
      docker-image: ${{ needs.linux-bionic-py3_8-clang9-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-bionic-py3_8-clang9-build.outputs.test-matrix }}
